on:
  pull_request:
    types: [opened, reopened, ready_for_review]
    branches: ["*"]
  issue_comment:
    types: [created]
  workflow_dispatch:

jobs:
  pr_agent_job:
    if: ${{ github.event.sender.type != 'Bot' && github.event.issue.pull_request }}
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
      issues: write
      contents: write
      checks: write
    name: PR Agent Automation
    steps:
      - name: Run PR Agent
        uses: qodo-ai/pr-agent@main
        env:
          OPENAI_KEY: ${{ secrets.OPEN_ROUTER_KEY }}
          GEMINI_API_KEY: ${{ secrets.GEMINI_API_KEY }}
          
          OPENAI_API_BASE: "https://openrouter.ai/api/v1"
          OPENAI_MODEL_NAME: "deepseek/deepseek-chat"
          GITHUB_TOKEN: ${{ github.token }}  # Changed to default token
          github_action_config.auto_review: "true"
          github_action_config.auto_describe: "true"
          github_action_config.auto_improve: "false"
          github_action_config.enable_comment_handling: "true"
          PR_CODE_SUGGESTIONS.NUM_CODE_SUGGESTIONS: 6
          github_action_config.pr_actions: '["opened", "reopened", "ready_for_review"]'
