on:
  pull_request:
    types: [opened, reopened, ready_for_review]
    branches: ["*"]
  issue_comment:
  workflow_dispatch:
jobs:
  pr_agent_job:
    if: ${{ github.event.sender.type != 'Bot' }}
    runs-on: ubuntu-latest
    permissions:
      issues: write
      pull-requests: write
      contents: write
    name: Run pr agent on every pull request, respond to user comments
    steps:
      - name: PR Agent action step
        id: pragent
        uses: qodo-ai/pr-agent@main
        env:
          OPENAI_KEY: ${{ secrets.OPEN_ROUTER_KEY }}
          OPENAI_API_BASE: "https://openrouter.ai/api/v1"
          OPENAI_MODEL_NAME: "deepseek/deepseek-chat"
          GITHUB_TOKEN: ${{ secrets.GIT_TOKEN }} # Make sure to add your GitHub token to your repo secrets
          github_action_config.auto_review: "true" # enable\disable auto review
          github_action_config.auto_describe: "true" # enable\disable auto describe
          github_action_config.auto_improve: "false" # enable\disable auto improve
          PR_CODE_SUGGESTIONS.NUM_CODE_SUGGESTIONS: 6
          github_action_config.pr_actions: '["opened", "reopened", "ready_for_review", "review_requested"]'
